--- 


spring: 
  jpa: 
    show-sql: true   
    Database: MYSQL
    

  h2:
    console:
      enabled: true 
    
    
  
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
   
  
  

---
spring:
    profiles:
      active:cloud


   