--- 
spring: 
  datasource: 
    password: rootdb
    url: "jdbc:mysql://localhost:3306/stsmsdb"
    username: root
  jpa: 
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  profiles: 
    name: local
---
spring:
   profiles: 
    name: cloud
---
spring:
    profiles:
      active:cloud

    
   